const REVALIDATE_CEP = 60 * 60 * 24 * 30
const REVALIDATE_IBGE = 60 * 60 * 24 * 180
const TIMEOUT_IBGE_MS = 2_000
const LIMITE_VIACEP = 50
const MINIMO_TERMO = 3
const ATRASO_SUGESTOES_MS = 300
const LIMITE_SUGESTOES = 50

export {
  ATRASO_SUGESTOES_MS,
  LIMITE_SUGESTOES,
  LIMITE_VIACEP,
  MINIMO_TERMO,
  REVALIDATE_CEP,
  REVALIDATE_IBGE,
  TIMEOUT_IBGE_MS,
}
